POST http://localhost:5000/v1/northwind/mutate
content-type: application/json

{
    "command": "insert into customers (`Company`, `Last Name`, `First Name`, `Job Title`, `Address`, `City`, `State/Province`, `ZIP/Postal Code`, `Country/Region`) VALUES (?,?,?,?,?,?,?,?,?)",
    "parameters": [
    "RyanCo",
    "Thompson",
    "Russell",
    "Developer",
    "12301 W Explorer Dr",
    "Boise",
    "ID",
    "83713",
    "USA"
    ]
}